version: '3'

services:
  broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /var/lib/mosquitto/config:/mosquitto/config
      - /var/lib/mosquitto/data:/mosquitto/data
      - /var/lib/mosquitto/log:/mosquitto/log
